server:
  port: 8080
spring:
  application:
    name: foo-service

# by default, all endpoints except for shutdown are enabled, however only for /health, /info and /docs
# can be accessed without authentication
management:
  security:
    enabled: false
