server:
  port: 8081
spring:
  application:
    name: bar-service

# by default, all endpoints except for shutdown are enabled, however only for /health, /info and /docs
# can be accessed without authentication

# the Actuator security features can be modified using management.security.
management:
  security:
    enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka/