server:
  port: 9999
spring:
  application:
    name: spring-boot-admin

management:
  security:
    enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka/